### ISSUE TITLE
Browserify + coverage doesn't work

### ISSUE THREAD

**Issue by chevalric** [karma-runner/karma-coverage#16]
If you use the karma-browserify plugin together with this plugin, it doesn't work. As far as I can tell, both preprocessors take the same files and then do their magic. What would actually be needed, is that the output of the first preprocessor is the input for the second one. Is there a solution to this?

**Comment by weikinhuang** [comment]
Hi, I found that using @eib's strategy works for generating code coverage reports, but it won't actually write the `html` reports with the following error:

```javascript
ERROR [coverage]: [TypeError: Cannot read property 'split' of undefined]
TypeError: Cannot read property 'split' of undefined
  at HtmlReport.Report.mix.writeDetailPage (D:\Documents and Settings\My Documents\Projects\Avalon-Core\Repository\node_modules\istanbul\lib\report\html.js:396:30)
  at D:\Documents and Settings\My Documents\Projects\Avalon-Core\Repository\node_modules\istanbul\lib\report\html.js:473:26
  at SyncFileWriter.extend.writeFile (D:\Documents and Settings\My Documents\Projects\Avalon-Core\Repository\node_modules\istanbul\lib\util\file-writer.js:57:9)
  at FileWriter.extend.writeFile (D:\Documents and Settings\My Documents\Projects\Avalon-Core\Repository\node_modules\istanbul\lib\util\file-writer.js:147:23)
  at D:\Documents and Settings\My Documents\Projects\Avalon-Core\Repository\node_modules\istanbul\lib\report\html.js:472:24
  at Array.forEach (native)
  at HtmlReport.Report.mix.writeFiles (D:\Documents and Settings\My Documents\Projects\Avalon-Core\Repository\node_modules\istanbul\lib\report\html.js:466:23)
  at D:\Documents and Settings\My Documents\Projects\Avalon-Core\Repository\node_modules\istanbul\lib\report\html.js:468:22
  at Array.forEach (native)
  at HtmlReport.Report.mix.writeFiles (D:\Documents and Settings\My Documents\Projects\Avalon-Core\Repository\node_modules\istanbul\lib\report\html.js:466:23)
  at HtmlReport.Report.mix.writeReport (D:\Documents and Settings\My Documents\Projects\Avalon-Core\Repository\node_modules\istanbul\lib\report\html.js:550:14)
  at D:\Documents and Settings\My Documents\Projects\Avalon-Core\Repository\node_modules\karma-coverage\lib\reporter.js:138:24
  at D:\Documents and Settings\My Documents\Projects\Avalon-Core\Repository\node_modules\karma\lib\helper.js:87:7
  at FSReqWrap.oncomplete (fs.js:77:15)
```

However if I allow istanbul's reporter to use the standard fslookup store, everything works fine and I'm able to get properly highlighted reports.

**Comment by alexbardas** [comment]
I'm getting the exact same error as above.

@weikinhuang how do you allow istanbul's reporter to use the standard fslookup store?

**Comment by weikinhuang** [comment]
@alexbardas per issue #123 downgrading to v0.2.6 solves it for now, until #124 is merged.

**Comment by alexbardas** [comment]
Thanks very much @weikinhuang , I confirm that it works. I hope your pull request will get accepted soon.

**Comment by rysilva** [comment]
@eib Sorry if I'm misunderstanding but I don't understand how the HTML coverage report can work.  Istambul is running on the transpiled ES5 code, so coverage numbers are based on that, not the original ES6 files.  That's what I'm seeing, am I missing something?

**Comment by Dignifiedquire** [comment]
Should be fixed in master, in the new release that's going out later today

**Comment by nmccready** [comment]
Why is this closed as none of the solutions appear to be working. browserify-istanbul still does not ignore dependencies. I guess this is more istanbul's problem?

**Comment by MathiasPaumgarten** [comment]
@eib well, about a year later, your answer still solved my issue. Thanks!

**Comment by deeperx** [comment]
This is still a problem.

**Comment by gauravsoni1** [comment]
Well is there some straight forward way karma-browserify and karma-coverage to work together since its 2016 now :) ?

**Comment by deeperx** [comment]
Better to use tools such as Mocha, Istanbul, Isparta etc as I'm doing right now. It's way easier to configure and manage as compared to use them behind a curtain like in Karma.

**Comment by stsvilik** [comment]
Isparta is pretty outdated and does not work correctly with ES6 - coverage seems to be out of sync with transmuted source. I have already pointed out a recipe here that works well with Karma, browserify and ES6, so here it is again - https://github.com/istanbuljs/babel-plugin-istanbul

**Comment by deeperx** [comment]
@stsvilik The point is not Isparta. Point is: *"Using tools directly"*. Thx anyway.

**Comment by stsvilik** [comment]
@deeperx What I've sent can be used w/o Karma (and probably works better too). My point though is if you're recommending tools, please make sure those tools are up to the task otherwise it'll waste valuable time for users (speaking from experience).

**Comment by deeperx** [comment]
@stsvilik Thanks for the clarification. But I was not recommending any tool. I've clearly described my point on my previous post already.
