### ISSUE TITLE
Migrate to use nyc from istanbul

### ISSUE THREAD

**Issue by RinMinase** [karma-runner/karma-coverage#375]
Upon installing, this shows up:
```
warning karma-coverage > istanbul@0.4.5: 
This module is no longer maintained, try this instead:
  npm i nyc
```

Would it be possible to move to use `nyc` instead of `istanbul`?

**Comment by dogoku** [comment]
I believe that warning is misleading, since`nyc`is a command line tool.
What we probably need is to migrate to one of the other istanbul packages like `istanbul-api` or `istanbul-coverage`

**Comment by coreyfarrell** [comment]
istanbul was also a command-line tool but yes the warning is inaccurate for how `karma-coverage` uses it.  Just to give you heads up we are planning to deprecate `istanbul-api` after the current semver-major.  A big part of the reason is that when we upgrade `istanbul-lib-source-maps` to use `source-map@^0.7.3` this will force some of those API's to become async.  Many of the most commonly used parts of `istanbul-api` simply re-export the real modules.  The modules which would likely be used by this module:
* istanbul-lib-instrument - modify sources to include coverage counters (alt babel-plugin-istanbul if babel is being used)
* istanbul-lib-coverage - merge coverage results from multiple tests into a single dataset for reporting
* istanbul-lib-source-maps - process source-maps before generating reports
* istanbul-lib-report - the reporting system
* istanbul-reports - these are the actual reports (text-summary report, html report, etc)

I noticed this bug while investigating another issue and wanted to share my knowledge of future plans so you don't switch to a module that we intend to stop supporting.

**Comment by dogoku** [comment]
haha, i was planning to work on a PR, glad you did

**Comment by Goran216** [comment]
Is there any work in progress to migrate to use nyc?

**Comment by dogoku** [comment]
> Is there any work in progress to migrate to use nyc?

PR #377 has already done the work.

**Comment by Goran216** [comment]
> > Is there any work in progress to migrate to use nyc?
> 
> PR #377 has already done the work, it just needs to be released

Any ETA for releasing it? What are we waiting for?

**Comment by dogoku** [comment]
no idea, maybe ask the maintainer @johnjbarton.
also try to sound less entitled next time. people are doing this in their own time, they have no obligation to serve your timeline...

**Comment by RinMinase** [comment]
Since #377 has been merged and released on v2.0.0 🎊, issue has been addressed. I'm now closing this issue.

**Comment by Aaronius** [comment]
When I install karma-coverage 2.0.1, I'm still seeing:

```
npm WARN deprecated istanbul@0.4.5: This module is no longer maintained, try this instead:
npm WARN deprecated   npm i nyc
npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
```

If I run `npm ls istanbul`, I see the following:

```
@adobe/alloy@0.0.1-alpha.8 /Users/aahardy/dev/alloy
└─┬ karma-coverage@2.0.1
  └── istanbul@0.4.5 
```

and in package-lock.json, I see:

```
    "karma-coverage": {
      "version": "2.0.1",
      "resolved": "https://registry.npmjs.org/karma-coverage/-/karma-coverage-2.0.1.tgz",
      "integrity": "sha512-SnFkHsnLsaXfxkey51rRN9JDLAEKYW2Lb0qOEvcruukk0NkSNDkjobNDZPt9Ni3kIhLZkLtpGOz661hN7OaZvQ==",
      "dev": true,
      "requires": {
        "dateformat": "^1.0.6",
        "istanbul": "^0.4.0",
        "istanbul-lib-coverage": "^2.0.5",
        "istanbul-lib-instrument": "^3.3.0",
        "istanbul-lib-report": "^2.0.8",
        "istanbul-lib-source-maps": "^3.0.6",
        "istanbul-reports": "^2.2.4",
        "lodash": "^4.17.11",
        "minimatch": "^3.0.0",
        "source-map": "^0.5.1"
      }
    },
```

I'm not sure why istanbul is marked as required there.
